# SPDX-License-Identifier: GPL-2.0+
# Copyright (C) 2019-2020 Maximilian Luz <luzmaximilian@gmail.com>

obj-m += surface_hotplug.o

#ccflags-y += -DDEBUG
ccflags-y += -Wall -Wextra
ccflags-y += -Wno-unused-parameter -Wno-missing-field-initializers
ccflags-y += -Wmaybe-uninitialized -Wuninitialized
